#!/usr/bin/env python3
"""
Upload parsed courses to Supabase.
Usage:
  1. Run the SQL schema in Supabase SQL Editor first
  2. Export SUPABASE_SERVICE_KEY
  3. Then run: python3 upload_courses.py
"""

import json
import os
from supabase import create_client

# ══════════════════════════════════════════
# CONFIGURATION - Update these values
# ══════════════════════════════════════════
SUPABASE_URL = "https://haioiccujncsehadipzb.supabase.co"
SERVICE_ROLE_KEY = os.environ.get("SUPABASE_SERVICE_KEY", "")
LANGUAGE_NAME = "Yoruba"  # Change for other languages
COURSES_FILE = os.path.join(os.path.dirname(__file__), "courses_parsed.json")  # Generated by the parser
# ══════════════════════════════════════════

def main():
    if not SERVICE_ROLE_KEY:
        raise SystemExit("SUPABASE_SERVICE_KEY is required")
    print("Connecting to Supabase...")
    supabase = create_client(SUPABASE_URL, SERVICE_ROLE_KEY)

    # Find language ID
    lang = supabase.table("languages").select("id").eq("name", LANGUAGE_NAME).execute()
    if not lang.data:
        print(f"ERROR: Language '{LANGUAGE_NAME}' not found in database!")
        return
    language_id = lang.data[0]["id"]
    print(f"Found language: {LANGUAGE_NAME} (id={language_id})")

    # Load parsed courses
    with open(COURSES_FILE, "r", encoding="utf-8") as f:
        courses = json.load(f)

    total_courses = 0
    total_lessons = 0
    total_items = 0

    for course_data in courses:
        print(f"\nUploading course: {course_data['title']}...")

        # Insert course
        course_icons = {
            "Construction phrasique": "🏗️",
            "Grammaire & Conjugaison": "📐",
            "Phrases utiles": "💬",
            "Vocabulaire par thème": "🏷️",
        }
        course = supabase.table("courses").insert({
            "language_id": language_id,
            "title": course_data["title"],
            "description": course_data["description"],
            "course_order": course_data["order"],
            "icon": course_icons.get(course_data["title"], "📚"),
        }).execute()
        course_id = course.data[0]["id"]
        total_courses += 1

        for lesson_idx, lesson_data in enumerate(course_data["lessons"]):
            # Insert lesson
            lesson_row = {
                "course_id": course_id,
                "title": lesson_data["title"],
                "lesson_order": lesson_idx + 1,
            }
            if "parent_theme" in lesson_data:
                lesson_row["parent_theme"] = lesson_data["parent_theme"]

            lesson = supabase.table("lessons").insert(lesson_row).execute()
            lesson_id = lesson.data[0]["id"]
            total_lessons += 1

            # Insert items in batches
            items_to_insert = []
            for item_idx, item in enumerate(lesson_data["items"]):
                row = {
                    "lesson_id": lesson_id,
                    "french": item["french"],
                    "dialect": item["dialect"],
                    "item_order": item_idx + 1,
                }
                if "example_french" in item:
                    row["example_french"] = item["example_french"]
                if "example_dialect" in item:
                    row["example_dialect"] = item["example_dialect"]
                items_to_insert.append(row)

            # Upload in batches of 50
            for i in range(0, len(items_to_insert), 50):
                batch = items_to_insert[i:i+50]
                supabase.table("lesson_items").insert(batch).execute()

            total_items += len(items_to_insert)
            print(f"  ✓ {lesson_data['title']}: {len(items_to_insert)} items")

    print(f"""
=======================================================
  COURSES UPLOAD COMPLETE!
=======================================================
  Language:   {LANGUAGE_NAME}
  Courses:    {total_courses}
  Lessons:    {total_lessons}
  Items:      {total_items}
=======================================================
""")

if __name__ == "__main__":
    main()
