import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(here, "..");
globalThis.window = {};
await import(path.join(projectRoot, "design-prototypes/course-trail/course-content.js"));

const { lessons } = globalThis.window.MONOKO_COURSE_CONTENT;
const capsuleLessons = lessons.filter(lesson => lesson.capsule);

function sql(value) {
  if (value === null || value === undefined || value === "") return "null";
  return `'${String(value).replaceAll("'", "''")}'`;
}

const values = capsuleLessons.map(lesson => {
  const item = lesson.capsule;
  const rewardXp = 40 + lesson.level * 10;
  return `  (${[
    sql(item.id), lesson.id, lesson.level, lessons.indexOf(lesson) + 1,
    sql(item.title), sql(item.region), sql(item.short), sql(item.body),
    sql(item.icon), sql(item.art), "null", sql(item.sourceLabel), sql(item.sourceUrl),
    sql("draft"), rewardXp, "true",
  ].join(", ")})`;
});

const output = `-- Generated by scripts/generate_culture_capsules_sql.mjs.
-- Edit course-content.js, then regenerate this file; do not hand-edit both.

begin;

-- Remove obsolete draft capsules for lessons managed by this course seed.
delete from culture_capsules
where lesson_id in (${lessons.map(lesson => lesson.id).join(", ")})
  and id not in (${capsuleLessons.map(lesson => sql(lesson.capsule.id)).join(", ")});

insert into culture_capsules (
  id, lesson_id, level, sort_order,
  title, region, short_copy, body_copy,
  icon, visual_key, image_url,
  source_label, source_url, review_status, reward_xp, is_published
)
values
${values.join(",\n")}
on conflict (id) do update set
  lesson_id = excluded.lesson_id,
  level = excluded.level,
  sort_order = excluded.sort_order,
  title = excluded.title,
  region = excluded.region,
  short_copy = excluded.short_copy,
  body_copy = excluded.body_copy,
  icon = excluded.icon,
  visual_key = excluded.visual_key,
  image_url = coalesce(excluded.image_url, culture_capsules.image_url),
  source_label = excluded.source_label,
  source_url = excluded.source_url,
  review_status = case
    when culture_capsules.review_status = 'draft' then excluded.review_status
    else culture_capsules.review_status
  end,
  reward_xp = excluded.reward_xp,
  is_published = excluded.is_published,
  updated_at = now();

commit;
`;

const target = path.join(projectRoot, "sql/culture_capsules_seed.sql");
await writeFile(target, output, "utf8");
console.log(`Wrote ${capsuleLessons.length} culture capsules to ${target}`);
